default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  host: db
  username: postgres
  password: password
  database: car_rent_api_development

test:
  <<: *default
  host: db
  username: postgres
  password: password
  database: car_rent_api_test

production:
  <<: *default
  host: <%= ENV['CAR_RENT_API_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['CAR_RENT_API_DATABASE_PORT'] || '5432' %>
  database: <%= ENV['CAR_RENT_API_DATABASE'] || 'car_rent_api_production' %>
  username: <%= ENV['CAR_RENT_API_DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['CAR_RENT_API_DATABASE_PASSWORD'] || 'password' %>
