default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: car_rent_api_development
  username: postgres
  password: password

test:
  <<: *default
  database: car_rent_api_test
  username: postgres
  password: password

production:
  <<: *default
  database: car_rent_api_production
  username: postgres
  password: <%= ENV["CAR_RENT_API_DATABASE_PASSWORD"] %>
